name: Release Compiler (AirLang)

on:
  push:
    tags:
      - 'compiler_v*'

permissions:
  contents: write

jobs:
  build:
    name: Build AirLang
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            ext: ""
          - os: windows-latest
            goos: windows
            ext: ".exe"
          - os: macos-latest
            goos: darwin
            ext: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build AirLang
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: amd64
        run: |
          mkdir -p artifacts
          cd Lang
          go build -o ../artifacts/AirLang_${{ matrix.goos }}${{ matrix.ext }} main.go

      - name: Upload Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/AirLang_*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
