name: Release Go and C Projects

on:
  push:
    tags:
      - 'v*' # Триггерится при создании тега, начинающегося с "v"
    branches:
      - master # Запускается только из ветки master

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout кода
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Установка Go
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20' # Укажите нужную версию Go

    # 3. Сборка Go-проекта
    - name: Build Go project
      run: |
        cd go
        go build -o ../artifacts/my_go_program main.go

    # 4. Сборка C-проекта
    - name: Build C project
      run: |
        cd c
        make
        mv my_c_program ../artifacts/

    # 5. Создание директории для артефактов
    - name: Create artifacts directory
      run: mkdir -p artifacts

    # 6. Архивация исполняемых файлов
    - name: Archive binaries
      run: |
        tar -czf artifacts/go_project.tar.gz -C artifacts my_go_program
        tar -czf artifacts/c_project.tar.gz -C artifacts my_c_program

    # 7. Публикация релиза
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/go_project.tar.gz
          artifacts/c_project.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
