name: Release Cross-Platform Binaries

on:
  push:
    tags:
      - 'v*'  

permissions:
  contents: write  # Разрешение на запись (необходимо для создания релиза)

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        goos: [linux, windows, darwin]
        include:
          - os: ubuntu-latest
            ext: ""
          - os: windows-latest
            ext: ".exe"
          - os: macos-latest
            ext: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install C dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build C project (AirVM)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd VM
          make clean
          make all

      - name: Build Go project (AirLang)
        run: |
          cd Lang
          GOOS=${{ matrix.goos }} GOARCH=amd64 go build -o ../artifacts/AirLang_${{ matrix.goos }}${{ matrix.ext }} main.go

      - name: Create artifacts directory
        run: mkdir -p artifacts

      - name: Copy binaries to artifacts
        run: |
          cp VM/bin/AirVM artifacts/AirVM || true
          cp Lang/AirLang_${{ matrix.goos }}${{ matrix.ext }} artifacts/ || true

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/AirVM
            artifacts/AirLang_${{ matrix.goos }}${{ matrix.ext }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
